name: "CodeQL IaC"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: "ubuntu-latest"
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize and Analyze IaC
        id: codeql_iac
        uses: advanced-security/codeql-extractor-iac@main

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.codeql_iac.outputs.sarif }}

      # New step to upload the SARIF file as an artifact
      - name: Upload SARIF as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: codeql-sarif
          path: ${{ steps.codeql_iac.outputs.sarif }}
